# Daftar seluruh emiten IDX (papan Utama, Pengembangan, Akselerasi, Ekonomi Baru --
# papan "Pemantauan Khusus" DIKECUALIKAN karena biasanya thin/suspend/berisiko).
#
# Sumber: wildangunawan/Dataset-Saham-IDX (github.com/wildangunawan/Dataset-Saham-IDX),
# lisensi CC BY-NC 4.0 (non-komersial, pakai atribusi -- OK untuk pemakaian personal).
# Data ini diupdate manual oleh pemilik repo, bisa sedikit ketinggalan untuk listing
# terbaru -- cukup untuk screening rutin, cek ulang berkala kalau mau presisi penuh.

ALL_IDX = [
    "AADI", "AALI", "ABMM", "ACES", "ACRO", "ACST", "ADCP", "ADES", "ADHI", "ADMF",
    "ADMG", "ADMR", "ADRO", "AGAR", "AGII", "AGRO", "AGRS", "AHAP", "AIMS", "AISA",
    "AKPI", "AKRA", "AKSI", "ALDO", "ALII", "ALKA", "AMAG", "AMAN", "AMAR", "AMFG",
    "AMIN", "AMMN", "AMMS", "AMOR", "AMRT", "ANJT", "ANTM", "APEX", "APIC", "APII",
    "APLI", "APLN", "ARCI", "AREA", "ARGO", "ARII", "ARKO", "ARNA", "ARTA", "ARTO",
    "ASBI", "ASDM", "ASGR", "ASII", "ASJT", "ASLC", "ASLI", "ASPI", "ASRI", "ASRM",
    "ASSA", "ATIC", "ATLA", "AUTO", "AVIA", "AWAN", "AXIO", "AYAM", "AYLS", "BABP",
    "BABY", "BACA", "BAIK", "BAJA", "BALI", "BANK", "BAPA", "BATA", "BATR", "BAYU",
    "BBCA", "BBHI", "BBKP", "BBLD", "BBMD", "BBNI", "BBRI", "BBRM", "BBSI", "BBSS",
    "BBTN", "BBYB", "BCAP", "BCIC", "BCIP", "BDKR", "BDMN", "BEEF", "BEER", "BELI",
    "BESS", "BEST", "BFIN", "BGTG", "BHAT", "BIKE", "BIMA", "BINA", "BINO", "BIPI",
    "BIRD", "BISI", "BJBR", "BJTM", "BKSW", "BLES", "BLUE", "BMBL", "BMHS", "BMRI",
    "BMSR", "BMTR", "BNBA", "BNGA", "BNII", "BNLI", "BOAT", "BOBA", "BOGA", "BOLA",
    "BOLT", "BPFI", "BPII", "BPTR", "BRAM", "BREN", "BRIS", "BRMS", "BRNA", "BRPT",
    "BRRC", "BSBK", "BSDE", "BSIM", "BSML", "BSSR", "BSWD", "BTPN", "BTPS", "BUAH",
    "BUDI", "BUKA", "BUKK", "BULL", "BUMI", "BUVA", "BVIC", "BWPT", "BYAN", "CAKK",
    "CAMP", "CARE", "CARS", "CASA", "CASH", "CASS", "CBDK", "CBPE", "CCSI", "CEKA",
    "CFIN", "CGAS", "CHEM", "CHIP", "CINT", "CITA", "CITY", "CLEO", "CLPI", "CMNP",
    "CMNT", "CMRY", "CNMA", "COCO", "CPIN", "CPRO", "CRAB", "CRSN", "CSAP", "CSRA",
    "CTRA", "CUAN", "CYBR", "DAAZ", "DART", "DATA", "DAYA", "DCII", "DEPO", "DEWA",
    "DEWI", "DFAM", "DGIK", "DGNS", "DGWG", "DILD", "DIVA", "DKFT", "DLTA", "DMAS",
    "DMMX", "DNAR", "DNET", "DOID", "DOOH", "DOSS", "DPNS", "DPUM", "DRMA", "DSFI",
    "DSNG", "DSSA", "DVLA", "DWGL", "DYAN", "EAST", "ECII", "EDGE", "EKAD", "ELIT",
    "ELPI", "ELSA", "EMDE", "EMTK", "ENAK", "ENRG", "EPMT", "ERAA", "ERAL", "ERTX",
    "ESSA", "ESTA", "EURO", "EXCL", "FAPA", "FAST", "FILM", "FIRE", "FITT", "FLMC",
    "FMII", "FOLK", "FOOD", "FORU", "FPNI", "FUJI", "FUTR", "FWCT", "GDYR", "GEMA",
    "GEMS", "GGRM", "GHON", "GJTL", "GLVA", "GMTD", "GOLD", "GOLF", "GOOD", "GOTO",
    "GPRA", "GPSO", "GRIA", "GRPH", "GRPM", "GSMF", "GTBO", "GTRA", "GULA", "GUNA",
    "GWSA", "GZCO", "HAIS", "HAJJ", "HALO", "HATM", "HBAT", "HDFA", "HEAL", "HELI",
    "HERO", "HEXA", "HGII", "HILL", "HITS", "HMSP", "HOKI", "HOMI", "HRTA", "HRUM",
    "HUMI", "HYGN", "IBOS", "ICBP", "IDEA", "IDPR", "IFII", "IFSH", "IGAR", "IKBI",
    "IKPM", "IMAS", "IMJS", "IMPC", "INAI", "INCI", "INCO", "INDF", "INDO", "INDR",
    "INDS", "INDX", "INDY", "INET", "INKP", "INOV", "INPC", "INPP", "INPS", "INRU",
    "INTD", "INTP", "IOTF", "IPAC", "IPCC", "IPCM", "IPOL", "IRRA", "ISAP", "ISAT",
    "ISEA", "ISSP", "ITIC", "ITMA", "ITMG", "JARR", "JAST", "JATI", "JAWA", "JAYA",
    "JECC", "JIHD", "JKON", "JMAS", "JPFA", "JRPT", "JSMR", "JSPT", "JTPE", "KAEF",
    "KBLI", "KBLM", "KDSI", "KDTN", "KEEN", "KEJU", "KETR", "KICI", "KIJA", "KING",
    "KINO", "KIOS", "KJEN", "KKGI", "KLAS", "KLBF", "KLIN", "KMDS", "KMTR", "KOBX",
    "KOCI", "KONI", "KOPI", "KPIG", "KRAS", "KRYA", "KSIX", "KUAS", "LABA", "LABS",
    "LAJU", "LCKM", "LEAD", "LFLO", "LIFE", "LION", "LIVE", "LMAX", "LMPI", "LOPI",
    "LPCK", "LPIN", "LPKR", "LPLI", "LPPF", "LPPS", "LRNA", "LSIP", "LTLS", "LUCK",
    "LUCY", "MAHA", "MAIN", "MANG", "MAPA", "MAPI", "MARI", "MARK", "MASA", "MASB",
    "MAXI", "MAYA", "MBAP", "MBMA", "MBSS", "MBTO", "MCAS", "MCOL", "MCOR", "MDIY",
    "MDKA", "MDKI", "MDLN", "MEDC", "MEDS", "MEGA", "MEJA", "MENN", "MERK", "MFIN",
    "MGLV", "MGRO", "MHKI", "MICE", "MIDI", "MIKA", "MITI", "MKAP", "MKPI", "MKTR",
    "MLBI", "MLIA", "MLPL", "MLPT", "MMIX", "MMLP", "MNCN", "MOLI", "MORA", "MPIX",
    "MPMX", "MPOW", "MPPA", "MPRO", "MPXL", "MRAT", "MREI", "MSIE", "MSIN", "MSJA",
    "MSKY", "MSTI", "MTDL", "MTEL", "MTLA", "MTMH", "MTWI", "MUTU", "MYOH", "MYOR",
    "NAIK", "NANO", "NASI", "NATO", "NAYZ", "NCKL", "NELY", "NEST", "NFCX", "NICE",
    "NICK", "NICL", "NIKL", "NINE", "NIRO", "NISP", "NOBU", "NRCA", "NSSS", "NTBK",
    "NZIA", "OASA", "OBAT", "OBMD", "OILS", "OKAS", "OLIV", "OMED", "OPMS", "PACK",
    "PALM", "PAMG", "PANI", "PANR", "PANS", "PART", "PBID", "PBSA", "PCAR", "PDES",
    "PDPP", "PEGE", "PEHA", "PEVE", "PGAS", "PGEO", "PGJO", "PGLI", "PICO", "PJAA",
    "PKPK", "PLAN", "PMJS", "PMMP", "PNBN", "PNBS", "PNGO", "PNIN", "PNLF", "PNSE",
    "POLU", "PORT", "POWR", "PPGL", "PPRE", "PPRI", "PRAY", "PRDA", "PRIM", "PSAB",
    "PSDN", "PSGO", "PSSI", "PTBA", "PTIS", "PTMP", "PTMR", "PTPP", "PTPS", "PTPW",
    "PTRO", "PTSN", "PTSP", "PUDP", "PURI", "PWON", "PYFA", "PZZA", "RAAM", "RAJA",
    "RALS", "RANC", "RATU", "RCCC", "RDTX", "RELF", "RELI", "RGAS", "RICY", "RIGS",
    "RISE", "RMKE", "RMKO", "RONY", "ROTI", "RSCH", "RSGK", "RUIS", "RUNS", "SAFE",
    "SAME", "SAMF", "SAPX", "SATU", "SBMA", "SCCO", "SCMA", "SCNP", "SDPC", "SDRA",
    "SEMA", "SFAN", "SGER", "SGRO", "SHID", "SHIP", "SICO", "SIDO", "SILO", "SIMP",
    "SIPD", "SKBM", "SKLT", "SKRN", "SLIS", "SMAR", "SMBR", "SMDM", "SMDR", "SMGA",
    "SMGR", "SMIL", "SMKL", "SMKM", "SMLE", "SMMA", "SMRA", "SMSM", "SNLK", "SOCI",
    "SOFA", "SOHO", "SOLA", "SONA", "SOTS", "SOUL", "SPMA", "SPRE", "SPTO", "SRAJ",
    "SRSN", "SRTG", "SSIA", "SSMS", "SSTM", "STAA", "STAR", "STRK", "STTP", "SULI",
    "SUNI", "SURE", "SURI", "SWID", "TALF", "TAPG", "TAYS", "TBIG", "TBLA", "TBMS",
    "TCID", "TCPI", "TEBE", "TECH", "TFAS", "TGKA", "TGUK", "TINS", "TIRA", "TKIM",
    "TLDN", "TLKM", "TMAS", "TMPO", "TNCA", "TOBA", "TOOL", "TOSK", "TOTL", "TOTO",
    "TOWR", "TPIA", "TPMA", "TRGU", "TRIM", "TRIN", "TRIS", "TRJA", "TRON", "TRST",
    "TRUK", "TRUS", "TSPC", "TUGU", "TYRE", "UANG", "UCID", "UDNG", "UFOE", "ULTJ",
    "UNIC", "UNIQ", "UNIT", "UNTD", "UNTR", "UNVR", "URBN", "UVCR", "VAST", "VERN",
    "VICI", "VICO", "VINS", "VISI", "VKTR", "VOKS", "VRNA", "VTNY", "WAPO", "WEGE",
    "WEHA", "WGSH", "WIDI", "WIFI", "WIIM", "WIKA", "WINE", "WINS", "WIRG", "WOMF",
    "WOOD", "WTON", "YOII", "YULE", "ZBRA", "ZONE", "ZYRX",
]
